version: "3.8"
services:

  database:
    container_name: postgres_db
    image: postgres:15.4-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - custom

  redis:
    container_name: redis_cache
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - custom


networks:
  custom:
    driver: bridge