class SchdeuleParserException(Exception):
    ...

class NotFoundGroupException(SchdeuleParserException):
    ...

class NotFoundWeekdayException(SchdeuleParserException):
    ...

class SundayWorkDayException(SchdeuleParserException):
    ...